general:
  # Commands to run when the WM has started. This is useful for running a
  # script or launching another application.
  # Example: The below command launches Zebar.
  startup_commands: ['shell-exec zebar', 'shell-exec powershell.exe -WindowStyle Hidden -ExecutionPolicy Bypass -File "%userprofile%/.glzr/glazewm/disable_lock.ps1"']

  # Commands to run just before the WM is shutdown.
  # Example: The below command kills Zebar.
  shutdown_commands: ['shell-exec taskkill /IM zebar.exe /F']
  
  lock_commands: ['shell-exec rundll32.exe user32.dll,LockWorkStation']

  # Commands to run after the WM config is reloaded.
  config_reload_commands: []

  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: false

  # Whether to switch back and forth between the previously focused
  # workspace when focusing the current workspace.
  toggle_workspace_on_refocus: false

  cursor_jump:
    # Whether to automatically move the cursor on the specified trigger.
    enabled: true

    # Trigger for cursor jump:
    # - 'monitor_focus': Jump when focus changes between monitors.
    # - 'window_focus': Jump when focus changes between windows.
    trigger: 'monitor_focus'

  # How windows should be hidden when switching workspaces.
  # - 'cloak': Recommended. Hides windows with no animation.
  # - 'hide': Legacy method (v3.5 and earlier) that has a brief animation,
  # but has stability issues with some apps.
  hide_method: 'cloak'

  # Affects which windows get shown in the native Windows taskbar. Has no
  # effect if `hide_method: 'hide'`.
  # - 'true': Show all windows (regardless of workspace).
  # - 'false': Only show windows from the currently shown workspaces.
  show_all_in_taskbar: false

gaps:
  # Whether to scale the gaps with the DPI of the monitor.
  scale_with_dpi: true

  # Gap between adjacent windows.
  inner_gap: '0px'

  # Gap between windows and the screen edge.
  outer_gap:
    top: '40px'
    right: '0px'
    bottom: '0px'
    left: '0px'

window_effects:
  # Visual effects to apply to the focused window.
  focused_window:
    # Highlight the window with a colored border.
    # ** Exclusive to Windows 11 due to API limitations.
    border:
      enabled: false
      color: '#8dbcff'

    # Remove the title bar from the window's frame. Note that this can
    # cause rendering issues for some applications.
    hide_title_bar:
      enabled: false

    # Change the corner style of the window's frame.
    # ** Exclusive to Windows 11 due to API limitations.
    corner_style:
      enabled: false
      # Allowed values: 'square', 'rounded', 'small_rounded'.
      style: 'square'

    # Change the transparency of the window.
    transparency:
      enabled: false
      # Can be something like '95%' or '0.95' for slightly transparent windows.
      # '0' or '0%' is fully transparent (and, by consequence, unfocusable).
      opacity: '95%'

  # Visual effects to apply to non-focused windows.
  other_windows:
    border:
      enabled: false
      color: '#a1a1a1'
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: false
      style: 'square'
    transparency:
      enabled: false
      opacity: '0%'

window_behavior:
  # New windows are created in this state whenever possible.
  # Allowed values: 'tiling', 'floating'.
  initial_state: 'tiling'

  # Sets the default options for when a new window is created. This also
  # changes the defaults for when the state change commands, like
  # `set-floating`, are used without any flags.
  state_defaults:
    floating:
      # Whether to center floating windows by default.
      centered: true

      # Whether to show floating windows as always on top.
      shown_on_top: false

    fullscreen:
      # Maximize the window if possible. If the window doesn't have a
      # maximize button, then it'll be fullscreen'ed normally instead.
      maximized: false

      # Whether to show fullscreen windows as always on top.
      shown_on_top: false

workspaces:
  - name: '1'
  - name: '2'
  - name: '3'
  - name: '4'
  - name: '5'
  - name: '6'
  - name: '7'
  - name: '8'
  - name: '9'
  # - name: 'A'
  - name: 'B'
    bind_to_monitor: 0
  - name: 'C'
    bind_to_monitor: 0
  - name: 'E'
    bind_to_monitor: 1
  - name: 'G'
    bind_to_monitor: 1
  - name: 'I'
    bind_to_monitor: 1
  - name: 'M'
    bind_to_monitor: 1
  - name: 'N'
    bind_to_monitor: 1
  - name: 'D'
    bind_to_monitor: 1
  - name: 'O'
    bind_to_monitor: 1
  - name: 'S'
    bind_to_monitor: 1
  - name: 'X'
    bind_to_monitor: 0
  - name: 'Y'

window_rules:
  - commands: ['ignore']
    match:
      # Ignores any Zebar windows.
      - window_process: { equals: 'zebar' }

      # Ignores picture-in-picture windows for browsers.
      - window_title: { regex: '[Pp]icture.in.[Pp]icture' }
        window_class: { regex: 'Chrome_WidgetWin_1|MozillaDialogClass' }

      # Ignore rules for various 3rd-party apps.
      - window_process: { equals: 'PowerToys' }
        window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }
      - window_process: { equals: 'PowerToys' }
        window_title: { regex: '.*? - Peek' }
      - window_process: { equals: 'Lively' }
        window_class: { regex: 'HwndWrapper' }
      - window_process: { equals: 'EXCEL' }
        window_class: { not_regex: 'XLMAIN' }
      - window_process: { equals: 'WINWORD' }
        window_class: { not_regex: 'OpusApp' }
      - window_process: { equals: 'POWERPNT' }
        window_class: { not_regex: 'PPTFrameClass' }

# binding_modes:
#   # When enabled, the focused window can be resized via arrow keys or HJKL.
#   - name: 'resize'
#     keybindings:
#       - commands: ['resize --width -2%']
#         bindings: ['h', 'left']
#       - commands: ['resize --width +2%']
#         bindings: ['l', 'right']
#       - commands: ['resize --height +2%']
#         bindings: ['k', 'up']
#       - commands: ['resize --height -2%']
#         bindings: ['j', 'down']
#       # Press enter/escape to return to default keybindings.
#       - commands: ['wm-disable-binding-mode --name resize']
#         bindings: ['escape', 'enter']

keybindings:
  - commands: ['shell-exec powershell.exe "C:/Users/hector.bjernersjo/.glzr/glazewm/lock.bat"']
    bindings: ['LWin+Q']
  # Shift focus in a given direction.
  - commands: ['focus --direction left']
    bindings: ['LWin+h', 'LWin+left']
  - commands: ['focus --direction right']
    bindings: ['LWin+l', 'LWin+right']
  - commands: ['focus --direction up']
    bindings: ['LWin+k', 'LWin+up']
  - commands: ['focus --direction down']
    bindings: ['LWin+j', 'LWin+down']

  # Move focused window in a given direction.
  - commands: ['move --direction left']
    bindings: ['LWin+shift+h', 'LWin+shift+left']
  - commands: ['move --direction right']
    bindings: ['LWin+shift+l', 'LWin+shift+right']
  - commands: ['move --direction up']
    bindings: ['LWin+shift+k', 'LWin+shift+up']
  - commands: ['move --direction down']
    bindings: ['LWin+shift+j', 'LWin+shift+down']

  # Resize focused window by a percentage or pixel amount.
  - commands: ['resize --width -2%']
    bindings: ['LWin+ctrl+l']
  - commands: ['resize --width +2%']
    bindings: ['LWin+ctrl+k']
  - commands: ['resize --height +2%']
    bindings: ['LWin+ctrl+j']
  - commands: ['resize --height -2%']
    bindings: ['LWin+ctrl+k']

  # Disables window management and all other keybindings until alt+shift+p
  # is pressed again.
  - commands: ['wm-toggle-pause']
    bindings: ['alt+shift+p']

  # Change tiling direction. This determines where new tiling windows will
  # be inserted.
  - commands: ['toggle-tiling-direction']
    bindings: ['alt+v']

  # Change focus from tiling windows -> floating -> fullscreen.
  - commands: ['wm-cycle-focus']
    bindings: ['alt+space']

  # Change the focused window to be floating.
  - commands: ['toggle-floating --centered']
    bindings: ['LWin+v']

  # Change the focused window to be tiling.
  - commands: ['toggle-tiling']
    bindings: ['alt+t']

  # Change the focused window to be fullscreen.
  - commands: ['toggle-fullscreen']
    bindings: ['LWin+p']

  # Minimize focused window.
  - commands: ['toggle-minimized']
    bindings: ['LWin+u']

  # Close focused window.
  - commands: ['close']
    bindings: ['LWin+w']

  # Kill GlazeWM process safely.
  - commands: ['wm-exit']
    bindings: ['alt+shift+e']

  # Re-evaluate configuration file.
  - commands: ['wm-reload-config']
    bindings: ['alt+shift+r']

  # Redraw all windows.
  - commands: ['wm-redraw']
    bindings: ['alt+shift+w']

  # Focus the next/previous active workspace defined in `workspaces` config.
  - commands: ['focus --next-active-workspace']
    bindings: ['alt+I']
  - commands: ['focus --prev-active-workspace']
    bindings: ['alt+O']

  # Focus the workspace that last had focus.
  # - commands: ['focus --recent-workspace']
  #   bindings: ['alt+d']

  # Change focus to a workspace defined in `workspaces` config.
  - commands: ['focus --workspace 1']
    bindings: ['LWin+1']
  - commands: ['focus --workspace 2']
    bindings: ['LWin+2']
  - commands: ['focus --workspace 3']
    bindings: ['LWin+3']
  - commands: ['focus --workspace 4']
    bindings: ['LWin+4']
  - commands: ['focus --workspace 5']
    bindings: ['LWin+5']
  - commands: ['focus --workspace 6']
    bindings: ['LWin+6']
  - commands: ['focus --workspace 7']
    bindings: ['LWin+7']
  - commands: ['focus --workspace 8']
    bindings: ['LWin+8']
  - commands: ['focus --workspace 9']
    bindings: ['LWin+9']
  - commands: ['focus --workspace A']


  #   bindings: ['LWin+A']
  - commands: ['focus --workspace B']
    bindings: ['LWin+B']
  - commands: ['focus --workspace C']
    bindings: ['LWin+C']
  # - commands: ['focus --workspace D']
  #   bindings: ['LWin+D']
  - commands: ['focus --workspace E']
    bindings: ['LWin+E']
  # - commands: ['focus --workspace G']
  #   bindings: ['LWin+G']
  - commands: ['focus --workspace I']
    bindings: ['LWin+I']
  - commands: ['focus --workspace M']
    bindings: ['LWin+M']
  - commands: ['focus --workspace O']
    bindings: ['LWin+O']
  - commands: ['focus --workspace S']
    bindings: ['LWin+S']
  - commands: ['focus --workspace X']
    bindings: ['LWin+X']
  - commands: ['focus --workspace Y']
    bindings: ['LWin+Y']
  - commands: ['focus --workspace N']
    bindings: ['LWin+N']
  - commands: ['focus --workspace D']
    bindings: ['LWin+D']

  - commands: ['shell-exec powershell.exe -WindowStyle Hidden -ExecutionPolicy Bypass -File "%userprofile%/.glzr/glazewm/glaze_launcher.ps1"']
    bindings: ['LWin+enter']



  # Move the focused window's parent workspace to a monitor in a given
  # direction.
  - commands: ['move-workspace --direction left']
    bindings: ['LWin+shift+ctrl+H']
  - commands: ['move-workspace --direction right']
    bindings: ['LWin+shift+ctrl+L']
  - commands: ['move-workspace --direction up']
    bindings: ['LWin+shift+ctrl+K']
  - commands: ['move-workspace --direction down']
    bindings: ['LWin+shift+ctrl+J']

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ['move --workspace 1', 'focus --workspace 1']
    bindings: ['LWin+shift+1']
  - commands: ['move --workspace 2', 'focus --workspace 2']
    bindings: ['LWin+shift+2']
  - commands: ['move --workspace 3', 'focus --workspace 3']
    bindings: ['LWin+shift+3']
  - commands: ['move --workspace 4', 'focus --workspace 4']
    bindings: ['LWin+shift+4']
  - commands: ['move --workspace 5', 'focus --workspace 5']
    bindings: ['LWin+shift+5']
  - commands: ['move --workspace 6', 'focus --workspace 6']
    bindings: ['LWin+shift+6']
  - commands: ['move --workspace 7', 'focus --workspace 7']
    bindings: ['LWin+shift+7']
  - commands: ['move --workspace 8', 'focus --workspace 8']
    bindings: ['LWin+shift+8']
  - commands: ['move --workspace 9', 'focus --workspace 9']
    bindings: ['LWin+shift+9']

  - commands: ['move --workspace A', 'focus --workspace A']
    bindings: ['LWin+shift+A']
  - commands: ['move --workspace B', 'focus --workspace B']
    bindings: ['LWin+shift+B']
  - commands: ['move --workspace C', 'focus --workspace C']
    bindings: ['LWin+shift+C']
  - commands: ['move --workspace D', 'focus --workspace D']
    bindings: ['LWin+shift+D']
  - commands: ['move --workspace E', 'focus --workspace E']
    bindings: ['LWin+shift+E']
  - commands: ['move --workspace G', 'focus --workspace G']
    bindings: ['LWin+shift+G']
  - commands: ['move --workspace I', 'focus --workspace I']
    bindings: ['LWin+shift+I']
  - commands: ['move --workspace M', 'focus --workspace M']
    bindings: ['LWin+shift+M']
  - commands: ['move --workspace N', 'focus --workspace N']
    bindings: ['LWin+shift+N']
  - commands: ['move --workspace D', 'focus --workspace D']
    bindings: ['LWin+shift+D']
  - commands: ['move --workspace O', 'focus --workspace O']
    bindings: ['LWin+shift+O']
  - commands: ['move --workspace S', 'focus --workspace S']
    bindings: ['LWin+shift+S']
  - commands: ['move --workspace X', 'focus --workspace X']
    bindings: ['LWin+shift+X']
  - commands: ['move --workspace Y', 'focus --workspace Y']
    bindings: ['LWin+shift+Y']
